project_id = "bcjechewkjygyjoczcri"

[functions.verify-session-password]
verify_jwt = false

[functions.update-session-settings]
verify_jwt = false

[functions.cleanup-expired-session]
verify_jwt = false
